CREATE TABLE IF NOT EXISTS memory_videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    memory_id INT NOT NULL,
    video VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
);
